export const ACTIONS = {
    NOTIFY: 'NOTIFY',
    AUTH: 'AUTH',
    ADD_VISA_APPLICATIONS: 'ADD_VISA_APPLICATIONS',
    ADD_JOB_APPLICATIONS: 'ADD_JOB_APPLICATIONS',
    ADD_LOAN_APPLICATIONS: 'ADD_LOAN_APPLICATIONS',
    ADD_PAYMENT: 'ADD_PAYMENT',
    ADD_USERS: 'ADD_USERS',
}
export const REGISTER_ACTIONS = {
    CHANGE_INPUTS: 'CHANGE_INPUTS',
    
}
export const VISA_APPLICANT_ACTIONS = {
    CHANGE_VISA_APPLICANTS_PERSONAL_INPUTS: 'CHANGE_VISA_APPLICANTS_PERSONAL_INPUTS',
    CHANGE_VISA_APPLICANTS_PASSPORT_INPUTS: 'CHANGE_VISA_APPLICANTS_PASSPORT_INPUTS',
    CHANGE_VISA_APPLICANTS_VISA_INPUTS: 'CHANGE_VISA_APPLICANTS_VISA_INPUTS',
    CHANGE_VISA_APPLICANTS_HOME_INPUTS: 'CHANGE_VISA_APPLICANTS_HOME_INPUTS',
    CHANGE_VISA_APPLICANTS_BANK_INPUTS: 'CHANGE_VISA_APPLICANTS_BANK_INPUTS',
    CHANGE_VISA_APPLICANTS_MEDICAL_INPUTS: 'CHANGE_VISA_APPLICANTS_MEDICAL_INPUTS',
    CHANGE_VISA_APPLICANTS_CONTACT_INPUTS: 'CHANGE_VISA_APPLICANTS_CONTACT_INPUTS',
}
export const LOAN_APPLICANT_ACTIONS = {
    CHANGE_LOAN_APPLICANTS_LOAN_INPUTS: 'CHANGE_LOAN_APPLICANTS_LOAN_INPUTS',
    CHANGE_LOAN_APPLICANTS_INPUTS: 'CHANGE_LOAN_APPLICANTS_INPUTS',
    CHANGE_LOAN_APPLICANTS_FATHER_INPUTS: 'CHANGE_LOAN_APPLICANTS_FATHER_INPUTS',
    CHANGE_LOAN_APPLICANTS_MOTHER_INPUTS: 'CHANGE_LOAN_APPLICANTS_MOTHER_INPUTS',
    CHANGE_LOAN_APPLICANTS_LAND_INPUTS: 'CHANGE_LOAN_APPLICANTS_LAND_INPUTS',
    CHANGE_LOAN_APPLICANTS_BANK_INPUTS: 'CHANGE_LOAN_APPLICANTS_BANK_INPUTS',
    CHANGE_LOAN_APPLICANTS_COMMUNICATION_INPUTS: 'CHANGE_LOAN_APPLICANTS_COMMUNICATION_INPUTS',
}
export const JOB_APPLICANT_ACTIONS = {
    CHANGE_JOB_APPLICANTS_JOB_INPUTS: 'CHANGE_JOB_APPLICANTS_JOB_INPUTS',
    CHANGE_JOB_APPLICANTS_INPUTS: 'CHANGE_JOB_APPLICANTS_INPUTS',
    CHANGE_JOB_APPLICANTS_PASSPORT_INPUTS: 'CHANGE_JOB_APPLICANTS_PASSPORT_INPUTS',
    CHANGE_JOB_APPLICANTS_CONTACT_INPUTS: 'CHANGE_JOB_APPLICANTS_CONTACT_INPUTS'
}
export const PAYMENT_ACTIONS = {
    CHANGE_PAYMENT_INPUTS: 'CHANGE_PAYMENT_INPUTS',
}
export const JOBS_ACTIONS = {
    CHANGE_JOBS_CREATE_INPUTS: 'CHANGE_JOBS_CREATE_INPUTS',
}

