export const initialState = {
    register: {
         name: '',
         email: '',
         password: '',
         cf_password: '',
         code: ''
    },
    visaApplicant: {
        personalInfo: {
           IdentityCard: '',
           IdCardNumber: '',
           fullName: '',
           fathersName: '',
           mothersName: '',
           streetAddress: '',
           streetAddressLine2: '',
           city: '',
           province: '',
           postal: '',
           gender: '',
           dateOfBirth: '',
           dateOfIdCardIssue: '',
           religion: '',
           nationality: '',
           bloodGroup: '',
           maritalStatus: '',
           frontPhotoOfIdCard: '',
           backPhotoOfIdCard: '',
           photo: '',
           signature: '',

        },
        passportInfo: {
           passportCountry: '',
           passportNumber: '',
           passportIssuingAuthority: '',
           passportDateOfBirth: '',
           passportDateOfIssue: '',
           passportDateOfExpiry: '',
           passportDocument: '',
        },
        visaProcessingInfo: {
           wishedCountry: '',
           visaType: '',
           marriageCertificate: '',
           wishedStayDuration: '',
           isWishingCitizenship: '',
        },
        home: {
           locatedAtHome: '',
           homeStreetAddress: '',
           homeStreetAddressLine2: '',
           homeCity: '',
           homeProvince: '',
           homePostal: '',
           homeStayDuration: '',
           familyDependentOn: '',
           currentJob: '',
           monthlyIncome: '',
           familyMember: '',
           educationalQualification: '',
           languages: '',
           ieltsScore: '',
           ieltsDocument: '',

        },
        bank: {
           bankName: '',
           bankStateIssuDate: '',
           bankStateDocument: '',
        }, 
        medical: {
           hospitalName: '',
           MedicalReportIssueDate: '',
           MedicalReportDocument: '',
        },
        contact: {
           email: '',
           phone: '',
           homePhone: '',
        }
    },
    loanApplicant: {
        loanInfo: {
            visaApplyID: '',
            jobApplyID: '',
            totalRS: '444',
            loanAmount: '',
            amountOfMoney: '',
        },
        appliantInfo: {
            idNumber: '',
            frontPhotoOfIdCard: '',
            backPhotoOfIdCard: '',
            photoOfApplicant: '',
            signature: '',
        },
        fatherInfo: {
            isFatherPresent: '',
            fatherDeathCertificate: '',
            fatherIdNumber: '',
            fatherFrontPhotoOfIdCard: '',
            fatherBackPhotoOfIdCard: '',
            photoOfFather: '',
            signatureOfFather: '',
        },
        motherInfo: {
            isMotherPresent: '',
            motherDeathCertificate: '',
            motherIdNumber: '',
            motherFrontPhotoOfIdCard: '',
            motherBackPhotoOfIdCard: '',
            photoOfMother: '',
            signatureOfMother: '',
        },
        landDocument: {
            landLocation: '',
            landAmount: '',
            mediumOfGetting: '',
            plotNo: '',
            precursorDeathCertificate: '',
            inheritanceCertificate: '',
            houseLandDocuments: '',
            loanForm: '',
        },
        bankDetails: {
            bankName: '',
            accountIdNumber: '',
            bankBranchName: '',
            bankStatement: '',
        },
        communication: {
            email: '',
            phoneNumber: '',
            homePhoneNumber: '',
            comments: '',
        },
    },
    jobApplicant: {
        jobInfo: {
            fJobCountry: '',
            fJobNo: '',
            fJobSL: '',
            fJobName: '',
            fJobExperience: '',
            fJobExperienceCertificate: '',
            sJobCountry: '',
            sJobNo: '',
            sJobSL: '',
            sJobName: '',
            sJobExperience: '',
            sJobExperienceCertificate: '',
            tJobCountry: '',
            tJobNo: '',
            tJobSL: '',
            tJobName: '',
            tJobExperience: '',
            tJobExperienceCertificate: '',
            foJobCountry: '',
            foJobNo: '',
            foJobSL: '',
            foJobName: '',
            foJobExperience: '',
            foJobExperienceCertificate: '',
        },
        appliantInfo: {
            languages: '',
            nationality: '',
            nidCard: '',
            fullName: '',
            fathersName: '',
            mothersName: '',
            streetAddress: '',
            streetAddressLine2: '',
            city: '',
            province: '',
            postal: '',
            country: '',
            dateOfBirth: '',
            photo: '',
            signature: '',
        },
        passportVisaDetails: {
            passportCountry: '',
            passportNumber: '',
            passportDateOfIssue: '',
            passportDateOfExpiry: '',
            visaApplicationID: '',
            medicalReport: '',
        },
        communication: {
            email: '',
            phoneNumber: '',
            homePhoneNumber: '',
        },
    

    },
    paymentInfo: {
       firstName:'',
       lastName:'',
       address1:'',
       address2:'',
       city:'',
       customer_state:'',
       zip:'',
       country:'',
       visaApplyID: '',
       method:'',
       amount: '',
       bankReceipt: ''
    },
    jobs: {
        title: '',
        shortDescription: '',
        photo: '',
        file: '',
        method: ''
    },
    notify: {}, auth: {}, visaApplications: [], jobApplications: [], loanApplications: [], payments: [], users: [], 
}