export const loanInfo = [
            {value: "visaApplyID",
             label: "Visa Apply ID",
             type: "text"},
            {value: "jobApplyID",
             label: "Job Apply ID",
             type: "text"},
            {value: "totalRS",
             label: "Total Rs",
             type: "text"},
            {value: "loanAmount",
             label: "Loan Amount",
             type: "text"},
            {value: "amountOfMoney",
             label: "Amount of Money",
             type: "text"}
            ]
export const applicantInfo = [
            {value: "idNumber",
             label: "ID Card Number",
             type: "text"},
            {value: "frontPhotoOfIdCard",
             label: "Front Photo of your ID Card",
             type: "photo"},
            {value: "backPhotoOfIdCard",
             label: "Back Photo of your ID Card",
             type: "photo"},
            {value: "photoOfApplicant",
             label: "Your Photo",
             type: "photo"},
            {value: "signature",
             label: "Your Signature",
             type: "photo"}
            ]

export const fatherInfo = [
            {value: "isFatherPresent",
             label: "Father is",
             type: "text"},
            {value: "fatherDeathCertificate",
             label: "Death Certificate",
             type: "file"},
            {value: "fatherIdNumber",
             label: "ID Card Number",
             type: "text"},
            {value: "fatherFrontPhotoOfIdCard",
             label: "Front Photo of ID Card",
             type: "photo"},
            {value: "fatherBackPhotoOfIdCard",
             label: "Back Photo of ID Card",
             type: "photo"},
            {value: "photoOfFather",
             label: "Father's Photo",
             type: "photo"},
            {value: "signatureOfFather",
             label: "Signature",
             type: "photo"}
            ]
export const motherInfo = [
            {value: "isMotherPresent",
             label: "Mother is",
             type: "text"},
            {value: "motherDeathCertificate",
             label: "Death Certificate",
             type: "file"},
            {value: "motherIdNumber",
             label: "ID Card Number",
             type: "text"},
            {value: "motherFrontPhotoOfIdCard",
             label: "Front Photo of ID Card",
             type: "photo"},
            {value: "motherBackPhotoOfIdCard",
             label: "Back Photo of ID Card",
             type: "photo"},
            {value: "photoOfMother",
             label: "Mother's Photo",
             type: "photo"},
            {value: "signatureOfMother",
             label: "Signature",
             type: "photo"}
            ]
export const landInfo = [
            {value: "landLocation",
             label: "Where is the land located?",
             type: "text"},
            {value: "landAmount",
             label: "What is the total amount of land?",
             type: "text"},
            {value: "mediumOfGetting",
             label: "How did you get this property?",
             type: "text"},
            {value: "plotNo",
             label: "Plot no",
             type: "text"},
            {value: "precursorDeathCertificate",
             label: "Death Certificate",
             type: "file"},
            {value: "inheritanceCertificate",
             label: "Inheritance Certificate",
             type: "file"},
            {value: "houseLandDocuments",
             label: "Upload complete house land documents",
             type: "file"},
            {value: "loanForm",
             label: "Loan Form",
             type: "file"}
            ]
export const bankInfo = [
            {value: "bankName",
             label: "Bank Name",
             type: "text"},
            {value: "accountIdNumber",
             label: "Account ID Number",
             type: "text"},
            {value: "bankBranchName",
             label: "Bank Branch Name",
             type: "text"},
            {value: "bankStatement",
             label: "Bank Statement",
             type: "file"}
            ]
export const contactInfo = [
            {value: "email",
             label: "Email",
             type: "text"},
            {value: "phoneNumber",
             label: "Phone Number",
             type: "text"},
            {value: "homePhoneNumber",
             label: "Home Phone Number",
             type: "text"},
            {value: "comments",
             label: "Comments or Questions",
             type: "text"},
]