export const jobInfo = [
    {value: "fJobCountry",
     label: "Job Country Name",
     type: "text"},
    {value: "fJobNo",
     label: "Job Post No.",
     type: "text"},
    {value: "fJobSL",
     label: "Job SL No.",
     type: "text"},
    {value: "fJobName",
     label: "Job Name",
     type: "text"},
    {value: "fJobExperience",
     label: "How many years of experience do you have?",
     type: "text"},
    {value: "fJobExperienceCertificate",
     label: "Job Experience Certificate",
     type: "file"},
    {value: "sJobCountry",
     label: "Job Country Name",
     type: "text"},
    {value: "sJobNo",
     label: "Job Post No.",
     type: "text"},
    {value: "sJobSL",
     label: "Job SL No.",
     type: "text"},
    {value: "sJobName",
     label: "Job Name",
     type: "text"},
    {value: "sJobExperience",
     label: "How many years of experience do you have?",
     type: "text"},
    {value: "sJobExperienceCertificate",
     label: "Job Experience Certificate",
     type: "file"},
    {value: "tJobCountry",
     label: "Job Country Name",
     type: "text"},
    {value: "tJobNo",
     label: "Job Post No.",
     type: "text"},
    {value: "tJobSL",
     label: "Job SL No.",
     type: "text"},
    {value: "tJobName",
     label: "Job Name",
     type: "text"},
    {value: "tJobExperience",
     label: "How many years of experience do you have?",
     type: "text"},
    {value: "tJobExperienceCertificate",
     label: "Job Experience Certificate",
     type: "file"},
    {value: "foJobCountry",
     label: "Job Country Name",
     type: "text"},
    {value: "foJobNo",
     label: "Job Post No.",
     type: "text"},
    {value: "foJobSL",
     label: "Job SL No.",
     type: "text"},
    {value: "foJobName",
     label: "Job Name",
     type: "text"},
    {value: "foJobExperience",
     label: "How many years of experience do you have?",
     type: "text"},
    {value: "foJobExperienceCertificate",
     label: "Job Experience Certificate",
     type: "file"}
    ] 
export const applicantInfo = [
    {value: "languages",
     label: "How many languages do you know?",
     type: "text"},
    {value: "nationality",
     label: "What is your nationality?",
     type: "text"},
    {value: "nidCard",
     label: "National ID card Number",
     type: "text"},
    {value: "firstName",
     label: "First Name",
     type: "text"},
    {value: "middleName",
     label: "Middle Name",
     type: "text"},
    {value: "surname",
     label: "Surname",
     type: "text"},
    {value: "fathersNameFirst",
     label: "Father's First Name",
     type: "text"},
    {value: "fathersNameMiddle",
     label: "Father's Middle Name",
     type: "text"},
    {value: "fathersNameSurname",
     label: "Father's Surname",
     type: "text"},
    {value: "mothersNameFirst",
     label: "Mother's First Name",
     type: "text"},
    {value: "mothersNameMiddle",
     label: "Mother's Middle Name",
     type: "text"},
    {value: "mothersNameSurname",
     label: "Mother's Surname",
     type: "text"},
    {value: "streetAddress",
     label: "Street Address",
     type: "text"},
    {value: "streetAddressLine2",
     label: "Street Address Line 2",
     type: "text"},
    {value: "city",
     label: "City",
     type: "text"},
    {value: "province",
     label: "State/Province",
     type: "text"},
    {value: "postal",
     label: "Postal/Zip Code",
     type: "text"},
    {value: "country",
     label: "Country",
     type: "text"},
    {value: "dateOfBirth",
     label: "Date of Birth",
     type: "text"},
    {value: "photo",
     label: "Your Photo",
     type: "photo"},
    {value: "signature",
     label: "Your Signature",
     type: "photo"}
    ]
export const passportVisaInfo = [
    {value: "passportCountry",
     label: "Passport Country Name",
     type: "text"},
    {value: "passportNumber",
     label: "Passport Number",
     type: "text"},
    {value: "passportDateOfIssue",
     label: "Date of Issue",
     type: "text"},
    {value: "passportDateOfExpiry",
     label: "Date of Expiry",
     type: "text"},
    {value: "visaApplicationID",
     label: "Visa Application ID",
     type: "text"},
    {value: "medicalReport",
     label: "Medical Report",
     type: "file"}
    ]
export const contactInfo = [
    {value: "email",
     label: "Email",
     type: "text"},
    {value: "phoneNumber",
     label: "Phone Number",
     type: "text"},
    {value: "homePhoneNumber",
     label: "Home Phone Number",
     type: "text"},
]